# Generated by Django 4.1.3 on 2024-09-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='ไม่มีคำอธิบาย'),
        ),
    ]
